In [48]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from math import sqrt

In [98]:
df = pd.read_csv("andan-2022-autumn-lab-3/train.csv")
df_test = pd.read_csv("andan-2022-autumn-lab-3/test_x.csv")
df.head(100)

,user_id,org_id,rating,ts,user_city,org_city,average_bill,rating_org,rubrics,food_delivery,...,call_button,wheelchair_accessible,table_games,vinotheque,cakes_for_different_occasions,accepted_credit_cards,kalyan,teahouse,bread_from_tandoor,handmade_goods
0,12182789761588196310,11946401375069641937,4.0,677,msk,msk,1500.0,3.883212,Ресторан,1,...,0,0,0,0,0,0,0,0,0,0
1,2796544982129273287,5545859981678495568,5.0,577,msk,msk,1000.0,4.495379,Ресторан,1,...,0,0,0,0,0,0,0,0,0,0
2,10546824832088319728,3451485117888180206,4.0,716,msk,msk,500.0,4.576063,Кафе,1,...,0,0,0,0,0,0,0,0,0,0
3,9967742981458207920,9490041040735762889,3.0,639,spb,spb,1000.0,3.775701,Кафе,1,...,0,0,0,0,0,0,0,0,0,0
4,11046819495825038093,5234254278902729372,5.0,669,msk,msk,500.0,4.187500,Пиццерия,1,...,0,1,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,6803848117584995315,5700798010712829946,3.0,369,msk,msk,NaN,4.553071,Кофейня,0,...,0,0,0,0,0,0,0,0,0,0
96,7892918660746826523,6556420723466820988,3.0,655,msk,msk,NaN,4.295998,Кафе,1,...,0,0,0,0,0,0,0,0,0,0
97,15590309144725028069,10650849505464817989,5.0,736,msk,msk,500.0,4.509202,Кафе,1,...,0,0,0,0,0,0,0,0,0,0
98,7541384106611888743,4144381289797380347,5.0,597,msk,spb,1500.0,4.057143,Ресторан,1,...,0,0,0,0,0,0,0,0,0,0
99,6332150196654936385,13815570531639386053,3.0,1134,spb,spb,NaN,4.055814,Быстрое питание,0,...,0,0,0,0,0,0,0,0,0,0

In [96]:
cor = df.corr().abs()
cor = cor.get("rating_org").sort_values()

C:\Users\Julko\AppData\Local\Temp\ipykernel_15124\580813889.py:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  cor = df.corr().abs()

In [97]:
print(cor[cor > 0.09].sort_values(ascending=False))

rating_org                1.000000
rating                    0.269386
comfort_dis_my            0.187232
cafe                      0.181062
toilet_for_disabled       0.173958
comfort_my                0.168933
parking_disabled          0.167170
payment_by_credit_card    0.154419
automatic_door            0.150909
wheelchair_access         0.121642
car_park                  0.119001
craft_beer                0.118856
gift_certificate          0.116835
food_delivery             0.105047
sports_broadcasts         0.095342
Name: rating_org, dtype: float64

In [99]:
df["comfort_dis_my"]=df["wheelchair_access"]+df["parking_disabled"]+df["toilet_for_disabled"]+df["elevator_wheelchair_accessible"]+df["wheelchair_accessible"]
df["comfort_my"]=df["automatic_door"]+df["elevator"]+df["call_button"]+df["air_conditioning"]+df["car_park"]
df["internet_my"]=max(df["wi_fi"]+df["internet access"])
df["takeaway_my"]=df["online_takeaway"]+df["takeaway"]
df["card_my"]=max(df["payment_by_credit_card"]+df["accepted_credit_cards"])
df["delivery_my"]=df["food_product_delivery"]+df["food_delivery"]+df["delivery"]+df["free_delivery"]

In [100]:
df_test["comfort_dis_my"]=df_test["wheelchair_access"]+df_test["parking_disabled"]+df_test["toilet_for_disabled"]+df_test["elevator_wheelchair_accessible"]+df_test["wheelchair_accessible"]
df_test["comfort_my"]=df_test["automatic_door"]+df_test["elevator"]+df_test["call_button"]+df_test["air_conditioning"]+df_test["car_park"]
df_test["internet_my"]=max(df_test["wi_fi"]+df_test["internet access"])
df_test["takeaway_my"]=df_test["online_takeaway"]+df_test["takeaway"]
df_test["card_my"]=max(df_test["payment_by_credit_card"]+df_test["accepted_credit_cards"])
df_test["delivery_my"]=df_test["food_product_delivery"]+df_test["food_delivery"]+df_test["delivery"]+df_test["free_delivery"]

In [146]:
X = pd.DataFrame(df, columns=["user_id","org_id","rating","ts","food_delivery","breakfast","takeaway","summer_terrace","business_lunch","payment_by_credit_card","coffee_to_go","closed_for_quarantine","online_takeaway","karaoke","special_menu","sports_broadcasts","food_court1","craft_beer","projector","gift_certificate","automatic_door","food_product_delivery","car_park","promotions","cafe","minimum_order","free_delivery","self_service_kiosks","has_restaurant","air_conditioning","pets","elevator","has_bar","privilege_tickets","organic_food","vip_zone","hall_capacity","face_control","show_program","music","chillout","dancefloor","dress_code","billiards","strip","ramp","around_the_clock_work1","pickup","farm_products","delivery","coffee_shop","call_button","table_games","vinotheque","cakes_for_different_occasions","accepted_credit_cards","kalyan","teahouse","bread_from_tandoor","handmade_goods"])
X_test = pd.DataFrame(df_test, columns=["user_id","org_id","rating","ts","food_delivery","breakfast","takeaway","summer_terrace","business_lunch","payment_by_credit_card","coffee_to_go","closed_for_quarantine","online_takeaway","karaoke","special_menu","sports_broadcasts","food_court1","craft_beer","projector","gift_certificate","automatic_door","food_product_delivery","car_park","promotions","cafe","minimum_order","free_delivery","self_service_kiosks","has_restaurant","air_conditioning","pets","elevator","has_bar","privilege_tickets","organic_food","vip_zone","hall_capacity","face_control","show_program","music","chillout","dancefloor","dress_code","billiards","strip","ramp","around_the_clock_work1","pickup","farm_products","delivery","coffee_shop","call_button","table_games","vinotheque","cakes_for_different_occasions","accepted_credit_cards","kalyan","teahouse","bread_from_tandoor","handmade_goods"])
Y = np.array(df['rating_org'])

In [147]:
from sklearn.neighbors import KNeighborsRegressor

model = KNeighborsRegressor(n_neighbors=5000)

In [148]:
model.fit(X, Y)

KNeighborsRegressor(n_neighbors=5000)

In [149]:
pred_y = model.predict(X_test)

In [150]:
print(pred_y)

[4.30062092 4.34252918 4.33052063 ... 4.30322361 4.3336596  4.32103031]

In [152]:
answer = pd.DataFrame({'rating_org' : pred_y})
answer.index.name = 'id'
print(answer)

       rating_org
id
0        4.300621
1        4.342529
2        4.330521
3        4.303286
4        4.319226
...           ...
24660    4.296850
24661    4.343152
24662    4.303224
24663    4.333660
24664    4.321030

[24665 rows x 1 columns]

In [154]:
answer.to_csv("submission.csv")