In [128]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from math import sqrt

In [129]:
df = pd.read_csv("andan-2022-autumn-lab-4/train.csv")
df_test = pd.read_csv("andan-2022-autumn-lab-4/test_x.csv")
df.head(100)

,city,floor,id,lat,lng,osm_amenity_points_in_0.001,osm_amenity_points_in_0.005,osm_amenity_points_in_0.0075,osm_amenity_points_in_0.01,osm_building_points_in_0.001,...,reform_house_population_500,reform_mean_floor_count_1000,reform_mean_floor_count_500,reform_mean_year_building_1000,reform_mean_year_building_500,region,total_square,street,date,realty_type
0,Ставрополь,NaN,COL_65683,45.011356,41.919273,7,71,144,225,0,...,969.0,8.439655,9.250000,1990.232759,1993.500000,Ставропольский край,31.0,S1842,2020-02-23,10
1,Омск,NaN,COL_159011,54.984833,73.387344,4,40,109,206,0,...,305.0,4.756410,4.333333,1960.346154,1956.291667,Омская область,150.0,S14290,2020-05-24,10
2,Белгород,NaN,COL_205850,50.576805,36.563267,0,9,22,44,0,...,533.0,6.435897,6.400000,1980.452991,1989.633333,Белгородская область,73.0,S25733,2020-06-28,10
3,Большой Исток,NaN,COL_229491,56.714413,60.792454,0,0,0,1,0,...,NaN,NaN,NaN,NaN,NaN,Свердловская область,438.0,S6985,2020-07-19,110
4,Новосибирск,1.0,COL_77283,55.055200,82.895810,0,25,50,101,0,...,1188.0,6.830065,6.672414,1974.045752,1974.637931,Новосибирская область,62.7,S4778,2020-03-01,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,Екатеринбург,NaN,COL_68068,56.857327,60.651157,3,65,142,221,0,...,968.0,6.611429,6.391304,1970.437500,1968.956522,Свердловская область,3852.0,S4015,2020-02-23,110
96,Северская,NaN,COL_72178,44.852310,38.663857,0,1,2,4,0,...,159.0,3.000000,3.166667,1981.409091,1983.416667,Краснодарский край,361.5,S7917,2020-03-01,110
97,Барнаул,1.0,COL_159850,53.337597,83.791080,0,55,93,143,0,...,663.0,4.736842,5.625000,1966.888158,1967.250000,Алтайский край,36.6,S2913,2020-05-24,10
98,Байкальск,NaN,COL_234505,51.519997,104.150580,2,37,40,43,0,...,635.0,2.776596,2.951613,1982.087912,1980.048387,Иркутская область,68.0,S8989,2020-07-19,100
99,Москва,1.0,COL_135742,55.567776,37.496180,4,16,29,34,0,...,296.0,13.933333,15.333333,2014.733333,2014.666667,Москва,110.8,S24016,2020-04-26,10

In [130]:
l = df.isna().sum()
print(l[l > 0])

floor                             130265
osm_city_nearest_population           35
reform_house_population_1000       10933
reform_house_population_500        20333
reform_mean_floor_count_1000       12513
reform_mean_floor_count_500        22538
reform_mean_year_building_1000     12163
reform_mean_year_building_500      22134
street                              1203
dtype: int64

In [131]:
df["floor"].fillna(-1, inplace=True)
df_test["floor"].fillna(-1, inplace=True)
df["osm_city_nearest_population"].fillna(df["osm_city_nearest_population"].mean(), inplace=True)
df_test["osm_city_nearest_population"].fillna(df["osm_city_nearest_population"].mean(), inplace=True)

In [132]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 206474 entries, 0 to 206473
Data columns (total 76 columns):
 #   Column                               Non-Null Count   Dtype
---  ------                               --------------   -----
 0   city                                 206474 non-null  object
 1   floor                                206474 non-null  float64
 2   id                                   206474 non-null  object
 3   lat                                  206474 non-null  float64
 4   lng                                  206474 non-null  float64
 5   osm_amenity_points_in_0.001          206474 non-null  int64
 6   osm_amenity_points_in_0.005          206474 non-null  int64
 7   osm_amenity_points_in_0.0075         206474 non-null  int64
 8   osm_amenity_points_in_0.01           206474 non-null  int64
 9   osm_building_points_in_0.001         206474 non-null  int64
 10  osm_building_points_in_0.005         206474 non-null  int64
 11  osm_building_points_in_0.0075        206474 non-null  int64
 12  osm_building_points_in_0.01          206474 non-null  int64
 13  osm_catering_points_in_0.001         206474 non-null  int64
 14  osm_catering_points_in_0.005         206474 non-null  int64
 15  osm_catering_points_in_0.0075        206474 non-null  int64
 16  osm_catering_points_in_0.01          206474 non-null  int64
 17  osm_city_closest_dist                206474 non-null  float64
 18  osm_city_nearest_name                206474 non-null  object
 19  osm_city_nearest_population          206474 non-null  float64
 20  osm_crossing_closest_dist            206474 non-null  float64
 21  osm_crossing_points_in_0.001         206474 non-null  int64
 22  osm_crossing_points_in_0.005         206474 non-null  int64
 23  osm_crossing_points_in_0.0075        206474 non-null  int64
 24  osm_crossing_points_in_0.01          206474 non-null  int64
 25  osm_culture_points_in_0.001          206474 non-null  int64
 26  osm_culture_points_in_0.005          206474 non-null  int64
 27  osm_culture_points_in_0.0075         206474 non-null  int64
 28  osm_culture_points_in_0.01           206474 non-null  int64
 29  osm_finance_points_in_0.001          206474 non-null  int64
 30  osm_finance_points_in_0.005          206474 non-null  int64
 31  osm_finance_points_in_0.0075         206474 non-null  int64
 32  osm_finance_points_in_0.01           206474 non-null  int64
 33  osm_healthcare_points_in_0.005       206474 non-null  int64
 34  osm_healthcare_points_in_0.0075      206474 non-null  int64
 35  osm_healthcare_points_in_0.01        206474 non-null  int64
 36  osm_historic_points_in_0.005         206474 non-null  int64
 37  osm_historic_points_in_0.0075        206474 non-null  int64
 38  osm_historic_points_in_0.01          206474 non-null  int64
 39  osm_hotels_points_in_0.005           206474 non-null  int64
 40  osm_hotels_points_in_0.0075          206474 non-null  int64
 41  osm_hotels_points_in_0.01            206474 non-null  int64
 42  osm_leisure_points_in_0.005          206474 non-null  int64
 43  osm_leisure_points_in_0.0075         206474 non-null  int64
 44  osm_leisure_points_in_0.01           206474 non-null  int64
 45  osm_offices_points_in_0.001          206474 non-null  int64
 46  osm_offices_points_in_0.005          206474 non-null  int64
 47  osm_offices_points_in_0.0075         206474 non-null  int64
 48  osm_offices_points_in_0.01           206474 non-null  int64
 49  osm_shops_points_in_0.001            206474 non-null  int64
 50  osm_shops_points_in_0.005            206474 non-null  int64
 51  osm_shops_points_in_0.0075           206474 non-null  int64
 52  osm_shops_points_in_0.01             206474 non-null  int64
 53  osm_subway_closest_dist              206474 non-null  float64
 54  osm_train_stop_closest_dist          206474 non-null  float64
 55  osm_train_stop_points_in_0.005       206474 non-null  int64
 56  osm_train_stop_points_in_0.0075      206474 non-null  int64
 57  osm_train_stop_points_in_0.01        206474 non-null  int64
 58  osm_transport_stop_closest_dist      206474 non-null  float64
 59  osm_transport_stop_points_in_0.005   206474 non-null  int64
 60  osm_transport_stop_points_in_0.0075  206474 non-null  int64
 61  osm_transport_stop_points_in_0.01    206474 non-null  int64
 62  per_square_meter_price               206474 non-null  float64
 63  reform_count_of_houses_1000          206474 non-null  int64
 64  reform_count_of_houses_500           206474 non-null  int64
 65  reform_house_population_1000         195541 non-null  float64
 66  reform_house_population_500          186141 non-null  float64
 67  reform_mean_floor_count_1000         193961 non-null  float64
 68  reform_mean_floor_count_500          183936 non-null  float64
 69  reform_mean_year_building_1000       194311 non-null  float64
 70  reform_mean_year_building_500        184340 non-null  float64
 71  region                               206474 non-null  object
 72  total_square                         206474 non-null  float64
 73  street                               205271 non-null  object
 74  date                                 206474 non-null  object
 75  realty_type                          206474 non-null  int64
dtypes: float64(17), int64(53), object(6)
memory usage: 119.7+ MB

In [133]:
cor = df.corr().abs()
cor = cor.get("per_square_meter_price").sort_values()

C:\Users\Julko\AppData\Local\Temp\ipykernel_6620\3434916841.py:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  cor = df.corr().abs()

In [134]:
print(cor[cor > 0.41].sort_values(ascending=False))

per_square_meter_price               1.000000
osm_city_nearest_population          0.551328
osm_catering_points_in_0.005         0.496335
osm_amenity_points_in_0.005          0.489408
osm_amenity_points_in_0.01           0.483147
osm_amenity_points_in_0.0075         0.482451
osm_catering_points_in_0.0075        0.481220
osm_catering_points_in_0.01          0.472006
osm_leisure_points_in_0.01           0.464199
osm_healthcare_points_in_0.01        0.463089
osm_shops_points_in_0.01             0.448706
osm_healthcare_points_in_0.0075      0.442801
osm_shops_points_in_0.0075           0.441139
osm_shops_points_in_0.005            0.440054
osm_amenity_points_in_0.001          0.439348
osm_crossing_points_in_0.01          0.435145
osm_transport_stop_points_in_0.01    0.433152
osm_finance_points_in_0.01           0.432395
osm_catering_points_in_0.001         0.428957
osm_offices_points_in_0.01           0.427026
osm_leisure_points_in_0.0075         0.422961
osm_finance_points_in_0.0075         0.422775
osm_healthcare_points_in_0.005       0.417532
osm_crossing_points_in_0.0075        0.414459
osm_offices_points_in_0.0075         0.414378
osm_offices_points_in_0.005          0.410427
Name: per_square_meter_price, dtype: float64

In [135]:
df["my_amenity_points"]    = df["osm_amenity_points_in_0.001"]+df["osm_amenity_points_in_0.005"]+df["osm_amenity_points_in_0.0075"]+df["osm_amenity_points_in_0.01"]
df["my_catering_points"]   = df["osm_crossing_points_in_0.001"]+df["osm_catering_points_in_0.005"]+df["osm_catering_points_in_0.0075"]+df["osm_catering_points_in_0.01"]
df["my_offices_points"]    = df["osm_finance_points_in_0.001"]+df["osm_finance_points_in_0.005"]+df["osm_finance_points_in_0.0075"]+df["osm_finance_points_in_0.01"]
df["my_building_points"]   = df["osm_building_points_in_0.001"]+df["osm_building_points_in_0.005"]+df["osm_building_points_in_0.0075"]+df["osm_building_points_in_0.01"]
df["my_crossing_points"]   = df["osm_crossing_points_in_0.001"]+df["osm_crossing_points_in_0.005"]+df["osm_crossing_points_in_0.0075"]+df["osm_crossing_points_in_0.01"]
df["my_culture_points"]    = df["osm_culture_points_in_0.001"]+df["osm_culture_points_in_0.005"]+df["osm_culture_points_in_0.0075"]+df["osm_culture_points_in_0.01"]
df["my_finances_points"]   = df["osm_finance_points_in_0.001"]+df["osm_finance_points_in_0.005"]+df["osm_finance_points_in_0.0075"]+df["osm_finance_points_in_0.01"]
df["my_healthcare_points"] = df["osm_healthcare_points_in_0.005"]+df["osm_healthcare_points_in_0.0075"]+df["osm_healthcare_points_in_0.01"]
df["my_historic_points"]   = df["osm_historic_points_in_0.005"]+df["osm_historic_points_in_0.0075"]+df["osm_historic_points_in_0.01"]
df["my_hotels_points"]     = df["osm_hotels_points_in_0.005"]+df["osm_hotels_points_in_0.0075"]+df["osm_hotels_points_in_0.01"]
df["my_leisure_points"]    = df["osm_leisure_points_in_0.005"]+df["osm_leisure_points_in_0.0075"]+df["osm_leisure_points_in_0.01"]
df["my_train_stop_points"]    = df["osm_train_stop_points_in_0.005"]+df["osm_train_stop_points_in_0.0075"]+df["osm_train_stop_points_in_0.01"]
df["my_transport_stop_points"] = df["osm_transport_stop_points_in_0.005"]+df["osm_transport_stop_points_in_0.0075"]+df["osm_transport_stop_points_in_0.01"]
df["my_shops_points"]          = df["osm_shops_points_in_0.001"] + df["osm_shops_points_in_0.005"] + df["osm_shops_points_in_0.0075"]+df["osm_shops_points_in_0.01"]
df["0.1"]   = df["osm_amenity_points_in_0.01"] + df["osm_catering_points_in_0.01"] + df["osm_finance_points_in_0.01"] + df["osm_building_points_in_0.01"] + df["osm_crossing_points_in_0.01"] +df["osm_culture_points_in_0.01"] +df["osm_shops_points_in_0.01"]
+ df["osm_finance_points_in_0.01"] + df["osm_healthcare_points_in_0.01"] + df["osm_historic_points_in_0.01"] + df["osm_hotels_points_in_0.01"] +  df["osm_leisure_points_in_0.01"] + df["osm_train_stop_points_in_0.01"] +df["osm_transport_stop_points_in_0.01"]

0          59
1          70
2          32
3           6
4          27
         ...
206469     16
206470      8
206471     48
206472    163
206473     59
Length: 206474, dtype: int64

In [136]:
df_test["my_amenity_points"]    = df_test["osm_amenity_points_in_0.001"]+df_test["osm_amenity_points_in_0.005"]+df_test["osm_amenity_points_in_0.0075"]+df_test["osm_amenity_points_in_0.01"]
df_test["my_catering_points"]   = df_test["osm_crossing_points_in_0.001"]+df_test["osm_catering_points_in_0.005"]+df_test["osm_catering_points_in_0.0075"]+df_test["osm_catering_points_in_0.01"]
df_test["my_offices_points"]    = df_test["osm_finance_points_in_0.001"]+df_test["osm_finance_points_in_0.005"]+df_test["osm_finance_points_in_0.0075"]+df_test["osm_finance_points_in_0.01"]
df_test["my_building_points"]   = df_test["osm_building_points_in_0.001"]+df_test["osm_building_points_in_0.005"]+df_test["osm_building_points_in_0.0075"]+df_test["osm_building_points_in_0.01"]
df_test["my_crossing_points"]   = df_test["osm_crossing_points_in_0.001"]+df_test["osm_crossing_points_in_0.005"]+df_test["osm_crossing_points_in_0.0075"]+df_test["osm_crossing_points_in_0.01"]
df_test["my_culture_points"]    = df_test["osm_culture_points_in_0.001"]+df_test["osm_culture_points_in_0.005"]+df_test["osm_culture_points_in_0.0075"]+df_test["osm_culture_points_in_0.01"]
df_test["my_finances_points"]   = df_test["osm_finance_points_in_0.001"]+df_test["osm_finance_points_in_0.005"]+df_test["osm_finance_points_in_0.0075"]+df_test["osm_finance_points_in_0.01"]
df_test["my_healthcare_points"] = df_test["osm_healthcare_points_in_0.005"]+df_test["osm_healthcare_points_in_0.0075"]+df_test["osm_healthcare_points_in_0.01"]
df_test["my_historic_points"]   = df_test["osm_historic_points_in_0.005"]+df_test["osm_historic_points_in_0.0075"]+df_test["osm_historic_points_in_0.01"]
df_test["my_hotels_points"]     = df_test["osm_hotels_points_in_0.005"]+df_test["osm_hotels_points_in_0.0075"]+df_test["osm_hotels_points_in_0.01"]
df_test["my_leisure_points"]    = df_test["osm_leisure_points_in_0.005"]+df_test["osm_leisure_points_in_0.0075"]+df_test["osm_leisure_points_in_0.01"]
df_test["my_train_stop_points"]    = df_test["osm_train_stop_points_in_0.005"]+df_test["osm_train_stop_points_in_0.0075"]+df_test["osm_train_stop_points_in_0.01"]
df_test["my_transport_stop_points"] = df_test["osm_transport_stop_points_in_0.005"]+df_test["osm_transport_stop_points_in_0.0075"]+df_test["osm_transport_stop_points_in_0.01"]
df_test["my_shops_points"]          = df_test["osm_shops_points_in_0.001"] + df_test["osm_shops_points_in_0.005"] + df_test["osm_shops_points_in_0.0075"]+df_test["osm_shops_points_in_0.01"]
df_test["0.1"]   = df_test["osm_amenity_points_in_0.01"] + df_test["osm_catering_points_in_0.01"] + df_test["osm_finance_points_in_0.01"] + df_test["osm_building_points_in_0.01"] + df_test["osm_crossing_points_in_0.01"] +df_test["osm_culture_points_in_0.01"] +df_test["osm_shops_points_in_0.01"]
+ df_test["osm_finance_points_in_0.01"] + df_test["osm_healthcare_points_in_0.01"] + df_test["osm_historic_points_in_0.01"] + df_test["osm_hotels_points_in_0.01"] +  df_test["osm_leisure_points_in_0.01"] + df_test["osm_train_stop_points_in_0.01"] +df_test["osm_transport_stop_points_in_0.01"]

0        61
1        12
2        24
3         7
4         5
         ..
68820     7
68821    24
68822    94
68823    83
68824    40
Length: 68825, dtype: int64

In [137]:
import sklearn as sk
from sklearn.linear_model import LinearRegression 
from math import log2

In [147]:
X = pd.DataFrame(df, columns=["0.1","my_amenity_points", "my_catering_points", "my_offices_points", "my_building_points", "my_crossing_points", "my_culture_points", "my_finances_points", "my_healthcare_points", "my_historic_points", "my_hotels_points", "my_leisure_points", "my_train_stop_points", "my_transport_stop_points", "my_shops_points", "floor", "lat","lng","osm_city_closest_dist", "osm_crossing_closest_dist","osm_subway_closest_dist","osm_train_stop_closest_dist","total_square","realty_type"])
X_test = pd.DataFrame(df_test, columns=["0.1","my_amenity_points", "my_catering_points", "my_offices_points", "my_building_points", "my_crossing_points", "my_culture_points", "my_finances_points", "my_healthcare_points", "my_historic_points", "my_hotels_points", "my_leisure_points", "my_train_stop_points", "my_transport_stop_points", "my_shops_points", "floor", "lat","lng","osm_city_closest_dist", "osm_crossing_closest_dist","osm_subway_closest_dist","osm_train_stop_closest_dist","total_square","realty_type"])
Y = np.array(df['per_square_meter_price'].apply(log2))

In [148]:
model = LinearRegression(normalize=True).fit(X, Y)

In [149]:
pred_y = model.predict(X_test)

In [150]:
answer = pd.DataFrame({'per_square_meter_price' : 2 ** pred_y})
answer.index.name = 'id'
print(answer)

       per_square_meter_price
id
0                73275.263184
1                28599.732098
2                56206.138678
3                49297.608830
4                54131.628218
...                       ...
68820            19338.347529
68821            31473.155244
68822           106145.615774
68823           145325.272540
68824            52019.607192

[68825 rows x 1 columns]

In [105]:
answer.to_csv("submission.csv")